from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime


# ==========================================
# 1. AI Extraction & Generation Schemas (Pydantic)
# ==========================================

class ResumeAnalysis(BaseModel):
    """Structured output for resume parsing by LLM"""
    technical_skills: List[str] = Field(
        default_factory=list,
        description="Explicit technical skills, tools, frameworks, and programming languages extracted from resume"
    )
    projects: List[str] = Field(
        default_factory=list,
        description="Key technical projects mentioned in the resume"
    )


class JobAnalysis(BaseModel):
    """Structured output for job description analysis by LLM"""
    required_skills: List[str] = Field(
        default_factory=list,
        description="Strictly required technical skills, languages, or tools mentioned in the JD"
    )
    preferred_skills: List[str] = Field(
        default_factory=list,
        description="Nice-to-have or preferred technical skills mentioned in the JD"
    )


class Question(BaseModel):
    """Adaptive interview question generated by LLM"""
    skill: str = Field(..., description="The high-level skill category being tested")
    topic: str = Field(..., description="The specific subtopic or concept being tested")
    difficulty: str = Field(..., description="Difficulty level: Beginner, Intermediate, or Advanced")
    question: str = Field(..., description="The conceptual or scenario-based interview question")
    reference_answer: Optional[str] = Field(default=None, description="Key points of the reference answer")
    evaluation_points: Optional[List[str]] = Field(default_factory=list, description="Specific concepts to look for during evaluation")


class Evaluation(BaseModel):
    """Evaluation result for candidate's answer by LLM"""
    score: int = Field(..., ge=0, le=100, description="Score between 0 and 100")
    correctness: str = Field(..., description="Correct, Partially Correct, or Incorrect")
    missing_concepts: List[str] = Field(
        default_factory=list,
        description="Key concepts or edge cases missed in the candidate's answer"
    )
    feedback: str = Field(..., description="Constructive, concise technical feedback")
    recommended_next_topic: str = Field(..., description="Targeted topic candidate should review next")


class PlannerRecommendation(BaseModel):
    """Adaptive recommendation calculated by the planner"""
    current_weakness: str
    recommended_topic: str
    difficulty: str
    reason: str
    next_action: str


# ==========================================
# 2. Database & Domain Models (API Schemas)
# ==========================================

class SkillItem(BaseModel):
    id: Optional[int] = None
    skill_name: str
    score: int = 0
    required: bool = False
    preferred: bool = False
    source: str = "resume"  # "resume", "job_required", "job_preferred", "taxonomy"
    matched: bool = False
    status: str = "gap"  # "strong", "moderate", "gap"


class GapItem(BaseModel):
    skill_name: str
    score: int
    importance: str  # "required" or "preferred"
    priority: int  # 1 (highest) to 10
    reason: str


class CandidateProfile(BaseModel):
    id: int
    name: str
    target_role: str
    created_at: datetime
    skills: List[SkillItem] = []
    projects: List[str] = []


class AnalysisResponse(BaseModel):
    candidate_id: int
    candidate_name: str
    target_role: str
    extracted_skills: List[str]
    projects: List[str]
    required_skills: List[str]
    preferred_skills: List[str]
    matched_skills: List[str]
    skill_gaps: List[GapItem]
    readiness: int  # 0 to 100 percentage
    recommended_focus: PlannerRecommendation


class EvaluationRequest(BaseModel):
    question_id: int
    answer: str


class EvaluationResponse(BaseModel):
    attempt_id: int
    skill: str
    topic: str
    question: str
    answer: str
    score: int
    correctness: str
    missing_concepts: List[str]
    feedback: str
    previous_skill_score: int
    new_skill_score: int
    recommended_next_topic: str
    next_recommendation: PlannerRecommendation


class QuestionAttemptItem(BaseModel):
    id: int
    skill: str
    topic: str
    difficulty: str
    question: str
    answer: Optional[str] = None
    score: Optional[int] = None
    correctness: Optional[str] = None
    missing_concepts: List[str] = []
    feedback: Optional[str] = None
    recommended_next_topic: Optional[str] = None
    created_at: datetime


class ProgressResponse(BaseModel):
    candidate_id: int
    target_role: str
    readiness: int
    strong_skills: List[SkillItem]
    skill_gaps: List[GapItem]
    recent_attempts: List[QuestionAttemptItem]
    current_recommendation: PlannerRecommendation
